# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  python: 3.8
  environment: environment.yml
