name: master
on: push
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        backend: ["ray", "mpi", "dask", "pymp", "pyseq"]
    env:
      UNIDIST_BACKEND: ${{matrix.backend}}
    name: test-ubuntu (backend ${{matrix.backend}}, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: unidist
          environment-file: environment.yml
          python-version: ${{matrix.python-version}}
          channel-priority: strict
          # we set use-only-tar-bz2 to false in order for conda to properly find new packages to be installed
          # for more info see https://github.com/conda-incubator/setup-miniconda/issues/264
          use-only-tar-bz2: false
      # we install pickle5 here as it is missing in Ray for python 3.7 from PyPI
      # remove this when we return Ray back to installation from conda-forge
      # see details in https://github.com/modin-project/unidist/issues/219
      - name: Pickle5 installation for python 3.7
        run: conda install pickle5 -c conda-forge
        if: matrix.python-version == '3.7'
      - name: Conda environment
        run: |
          conda info
          conda list
      - run: python -m pytest unidist/test/
        if: matrix.backend != 'mpi'
      # when using a directory to run with mpiexec MPI gets hung after executing tests
      # so we run the test files one by one
      - run: mpiexec -n 1 python -m pytest unidist/test/test_actor.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_async_actor.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_task.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_general.py
        if: matrix.backend == 'mpi'

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        backend: ["ray", "mpi", "dask", "pymp", "pyseq"]
    env:
      UNIDIST_BACKEND: ${{matrix.backend}}
    name: test-windows (backend ${{matrix.backend}}, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: unidist
          environment-file: environment.yml
          python-version: ${{matrix.python-version}}
          channel-priority: strict
          # we set use-only-tar-bz2 to false in order for conda to properly find new packages to be installed
          # for more info see https://github.com/conda-incubator/setup-miniconda/issues/264
          use-only-tar-bz2: false
      # we install pickle5 here as it is missing in Ray for python 3.7 from PyPI
      # remove this when we return Ray back to installation from conda-forge
      # see details in https://github.com/modin-project/unidist/issues/219
      - name: Pickle5 installation for python 3.7
        run: conda install pickle5 -c conda-forge
        if: matrix.python-version == '3.7'
      - name: Conda environment
        run: |
          conda info
          conda list
      - run: python -m pytest unidist/test/
        if: matrix.backend != 'mpi'
      # when using a directory to run with mpiexec MPI gets hung after executing tests
      # so we run the test files one by one
      - run: mpiexec -n 1 python -m pytest unidist/test/test_actor.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_async_actor.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_task.py
        if: matrix.backend == 'mpi'
      - run: mpiexec -n 1 python -m pytest unidist/test/test_general.py
        if: matrix.backend == 'mpi'
